[package]
name = "ntdoc"
version = "0.1.0"
edition = "2024"

[dependencies]
cursive = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
fuzzy-matcher = "0.3"
clipboard = "0.5.0"
